### ISSUE TITLE
Failing on three.quarks PiecewiseFunction & PiecewiseBezier functions.

### ISSUE THREAD

**Issue by andrewleek-droplab** [Alchemist0823/three.quarks-editor#32]
I am unable to run the editor locally, it is throwing errors regarding functions in the three.quarks package specifically functions in PiecewiseFunction.ts & PiecewiseBezier.ts

Property 'findFunction' is protected and only accessible within class 'PiecewiseFunction<T>' and its subclasses.
Property 'insertFunction' does not exist on type 'PiecewiseBezier'.
Property 'removeFunction' does not exist on type 'PiecewiseBezier'

**Comment by Alchemist0823** [comment]
Thank you for asking this. I think this is solved now.
